window.COACHLEAGUE_CONFIG = {
  "main": {
    "name": "CoachLeague",
    "ticker": "COACH",
    "contract": "",
    "pumpfunUrl": "",
    "dexPairUrl": "",
    "xUrl": "",
    "telegramUrl": "",
    "discordUrl": ""
  },
  "coaches": [
    {
      "rank": 1,
      "name": "Didier DeChampagne",
      "ticker": "DIDI",
      "country": "France",
      "image": "assets/coaches/01-didier-dechampagne.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 2,
      "name": "Luis de la Furia",
      "ticker": "LUIS",
      "country": "Spain",
      "image": "assets/coaches/02-luis-de-la-furia.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 3,
      "name": "Thomas Tuchels",
      "ticker": "TUCHELS",
      "country": "England",
      "image": "assets/coaches/03-thomas-tuchels.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 4,
      "name": "Mauricios Pochettinos",
      "ticker": "POCHET",
      "country": "United States",
      "image": "assets/coaches/04-mauricios-pochettinos.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 5,
      "name": "Javiero Aguirres",
      "ticker": "JAVI",
      "country": "Mexico",
      "image": "assets/coaches/05-javiero-aguirres.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 6,
      "name": "Carlos Ancelotti’s",
      "ticker": "CARLOS",
      "country": "Brazil",
      "image": "assets/coaches/06-carlos-ancelotti-s.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 7,
      "name": "Lionels Scalonis",
      "ticker": "LION",
      "country": "Argentina",
      "image": "assets/coaches/07-lionels-scalonis.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 8,
      "name": "Ronaldo Koemans",
      "ticker": "RONALDO",
      "country": "Netherlands",
      "image": "assets/coaches/08-ronaldo-koemans.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 9,
      "name": "Vincenzos Montellas",
      "ticker": "MONTELLAS",
      "country": "Turkey",
      "image": "assets/coaches/09-vincenzos-montellas.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 10,
      "name": "Robert Martínoz",
      "ticker": "ROBERT",
      "country": "Portugal",
      "image": "assets/coaches/10-robert-mart-noz.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 11,
      "name": "Hajim Moriyasus",
      "ticker": "HAJIM",
      "country": "Japan",
      "image": "assets/coaches/11-hajim-moriyasus.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 12,
      "name": "Murad Yakn",
      "ticker": "MURAD",
      "country": "Switzerland",
      "image": "assets/coaches/12-murad-yakn.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 13,
      "name": "Juliano Nagelsmanns",
      "ticker": "NAGELSMAN",
      "country": "Germany",
      "image": "assets/coaches/13-juliano-nagelsmanns.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 14,
      "name": "Myungo-bo Hongo",
      "ticker": "HONGO",
      "country": "South Korea",
      "image": "assets/coaches/14-myungo-bo-hongo.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 15,
      "name": "Rudie Garcias",
      "ticker": "RUDIE",
      "country": "Belgium",
      "image": "assets/coaches/15-rudie-garcias.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 16,
      "name": "Emerses Faés",
      "ticker": "EMERSES",
      "country": "Ivory Coast",
      "image": "assets/coaches/16-emerses-fa-s.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 17,
      "name": "Papeo Thiawo",
      "ticker": "THIAWO",
      "country": "Senegal",
      "image": "assets/coaches/17-papeo-thiawo.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 18,
      "name": "Ralfi Rangnicks",
      "ticker": "RALFI",
      "country": "Austria",
      "image": "assets/coaches/18-ralfi-rangnicks.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 19,
      "name": "Zlatkos Dalico",
      "ticker": "DALICO",
      "country": "Croatia",
      "image": "assets/coaches/19-zlatkos-dalico.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 20,
      "name": "Steven Clarken",
      "ticker": "STEVEN",
      "country": "Scotland",
      "image": "assets/coaches/20-steven-clarken.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 21,
      "name": "Bubistar",
      "ticker": "BUBISTAR",
      "country": "Cape Verde",
      "image": "assets/coaches/21-bubistar.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 22,
      "name": "Thomassen Christiansens",
      "ticker": "THOM",
      "country": "Panama",
      "image": "assets/coaches/22-thomassen-christiansens.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 23,
      "name": "Ståles Solbakkens",
      "ticker": "STALES",
      "country": "Norway",
      "image": "assets/coaches/23-st-les-solbakkens.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 24,
      "name": "Huggo Brooss",
      "ticker": "BROOSS",
      "country": "South Africa",
      "image": "assets/coaches/24-huggo-brooss.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 25,
      "name": "Néstoro Lorenzos",
      "ticker": "LORENZOS",
      "country": "Colombia",
      "image": "assets/coaches/25-n-storo-lorenzos.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 26,
      "name": "Sébastienn Desabree",
      "ticker": "DESABREE",
      "country": "Congo",
      "image": "assets/coaches/26-s-bastienn-desabree.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 27,
      "name": "Amirr Ghalenoeii",
      "ticker": "AMIRR",
      "country": "Iran",
      "image": "assets/coaches/27-amirr-ghalenoeii.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 28,
      "name": "Marceloo Bielsaa",
      "ticker": "BIELSAA",
      "country": "Uruguay",
      "image": "assets/coaches/28-marceloo-bielsaa.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 29,
      "name": "Darrenn Bazeleyy",
      "ticker": "DARRENN",
      "country": "New Zealand",
      "image": "assets/coaches/29-darrenn-bazeleyy.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 30,
      "name": "Hossamm Hassann",
      "ticker": "HASSAN",
      "country": "Egypt",
      "image": "assets/coaches/30-hossamm-hassann.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 31,
      "name": "Vladimirr Petkovicc",
      "ticker": "PETKOVICC",
      "country": "Algeria",
      "image": "assets/coaches/31-vladimirr-petkovicc.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 32,
      "name": "Sébastienn Mignée",
      "ticker": "MIGNÉE",
      "country": "Haiti",
      "image": "assets/coaches/32-s-bastienn-mign-e.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 33,
      "name": "Sergejj Barbarezz",
      "ticker": "SERGEJJ",
      "country": "Bosnia and Herzegovina",
      "image": "assets/coaches/33-sergejj-barbarezz.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 34,
      "name": "Jessee Marschh",
      "ticker": "JESSEE",
      "country": "Canada",
      "image": "assets/coaches/34-jessee-marschh.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 35,
      "name": "Jamall Sellamii",
      "ticker": "JAMALL",
      "country": "Jordan",
      "image": "assets/coaches/35-jamall-sellamii.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 36,
      "name": "Sebastiánn Beccacecee",
      "ticker": "SEBASTIÁNN",
      "country": "Ecuador",
      "image": "assets/coaches/36-sebasti-nn-beccacecee.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 37,
      "name": "Gustavoo Alfaroo",
      "ticker": "ALFAROO",
      "country": "Paraguay",
      "image": "assets/coaches/37-gustavoo-alfaroo.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 38,
      "name": "Tonyy Popovicc",
      "ticker": "TONYY",
      "country": "Australia",
      "image": "assets/coaches/38-tonyy-popovicc.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 39,
      "name": "Julenn Lopeteguii",
      "ticker": "JULENN",
      "country": "Qatar",
      "image": "assets/coaches/39-julenn-lopeteguii.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 40,
      "name": "Grahamm Arnoldd",
      "ticker": "ARNOLDD",
      "country": "Iraq",
      "image": "assets/coaches/40-grahamm-arnoldd.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 41,
      "name": "Fabioo Cannavaroo",
      "ticker": "FABIOO",
      "country": "Uzbekistan",
      "image": "assets/coaches/41-fabioo-cannavaroo.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 42,
      "name": "Grahamm Potterr",
      "ticker": "POTTERR",
      "country": "Sweden",
      "image": "assets/coaches/42-grahamm-potterr.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 43,
      "name": "Miroslavv Koubekk",
      "ticker": "KOUBEKK",
      "country": "Czech Republic",
      "image": "assets/coaches/43-miroslavv-koubekk.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 44,
      "name": "Sabrii Lamouchii",
      "ticker": "SABRII",
      "country": "Tunisia",
      "image": "assets/coaches/44-sabrii-lamouchii.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 45,
      "name": "Mohamedd Ouahbii",
      "ticker": "OUAHBII",
      "country": "Morocco",
      "image": "assets/coaches/45-mohamedd-ouahbii.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 46,
      "name": "Carloss Queirozz",
      "ticker": "CARLOSS",
      "country": "Ghana",
      "image": "assets/coaches/46-carloss-queirozz.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 47,
      "name": "Georgioss Doniss",
      "ticker": "DONNIS",
      "country": "Saudi Arabia",
      "image": "assets/coaches/47-georgioss-doniss.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    },
    {
      "rank": 48,
      "name": "Dickk Advocaatt",
      "ticker": "DICKK",
      "country": "Curaçao",
      "image": "assets/coaches/48-dickk-advocaatt.png",
      "contract": "",
      "pumpfunUrl": "",
      "dexPairUrl": "",
      "description": "Trade the tactics."
    }
  ]
};
